# ------------------------------------------- #
# 自定义🈴集 ▶ 去广告•签到•解锁等(全部来自网上搜集的，纯自用！请与我联系删除)
# ------------------------------------------- #

[rewrite_local]
# == 去首页•乐刻健身 ▶ lens.leoao.com
^https:\/\/lens\.leoao\.com\/lens\/conduct\/app\/rpc\/v2\/com\.lefit\.dubbo\.cms\.api\.front\.A.*$ url response-body "data":\s*\[.*?\] response-body "data":[]
^https:\/\/lens\.leoao\.com\/lens\/conduct\/app\/rpc\/v2\/com\.leoao\.guide\.api\.BffApi\/homePageTopFloor url reject-dict
^https:\/\/lens\.leoao\.com\/lens\/conduct\/app\/rpc\/v2\/com\.lefit\.dubbo\.cms\.api\.bff\.ClientFrontFacade\/getPopupAggregations url response-body "data":\s*\{[^}]*\} response-body "data": {}

# == 解锁•极简汇率 ▶ xremit.xcurrency.com, explorer.tratao.com
^https?:\/\/(xremit\.xcurrency|explorer.tratao)\.com\/api\/client\/xtool\/vip url script-response-body https://haohao.one/Rewrite/jijianhuilv.js

# == 跳过微信中转页面,解除被封链接 ▶ weixin110.qq.com, security.wechat.com
^https\:\/\/(weixin110\.qq|security\.wechat)\.com\/cgi-bin\/mmspamsupport-bin\/newredirectconfirmcgi\? url script-response-body https://haohao.one/Rewrite/WeChat110.js

# == 去广告•12306开屏广告 ▶ ad.12306.cn, mobile.12306.cn
^https:\/\/ad\.12306\.cn\/ad\/ser\/getAdList$ url script-analyze-echo-response https://haohao.one/Rewrite/12306.js

# == 去广告•交管12123 ▶ gab.122.gov.cn
^https:\/\/gab\.122\.gov\.cn\/eapp\/m\/sysquery\/adver$ url reject

# == 预约•i茅台 ▶ app.moutai519.com.cn //获取CK脚本
^https:\/\/app\.moutai519\.com\.cn\/xhr\/front\/mall\/message\/unRead\/query url script-request-header https://haohao.one/Rewrite/iMT.js

# == 短信转发 ▶ scan.call.f.360.cn,jprx.m.qq.com 
(^https?:\/\/scan\.call\.f\.360\.cn\/ios_message\.php|^https?:\/\/jprx\.m\.qq\.com\/forward) url script-request-body https://haohao.one/Rewrite/sms-forward.js


[mitm]
hostname = lens.leoao.com, app.moutai519.com.cn, gab.122.gov.cn, ad.12306.cn, mobile.12306.cn, weixin110.qq.com, security.wechat.com, xremit.xcurrency.com, explorer.tratao.com, scan.call.f.360.cn,jprx.m.qq.com