name: 自动抓取Sync机器人

on:
  schedule:
    # 每天 UTC 时间 3 点 0 分运行一次
    - cron: '0 3 * * *'
  workflow_dispatch:
    # 手动触发

permissions:
  contents: write

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - name: 设置 Node.js 20 环境
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 检出代码仓库
        uses: actions/checkout@v3

      - name: QX解析器 & Task脚本
        run: |
          curl -o QuantumultX/general/resource-parser.js https://raw.githubusercontent.com/KOP-XIAO/QuantumultX/master/Scripts/resource-parser.js || echo "resource-parser.js下载失败"
          curl -o QuantumultX/Task/check.js https://raw.githubusercontent.com/MCdasheng/QuantumultX/main/Streaming/check.js || echo "check.js下载失败"
          curl -o QuantumultX/Task/Sub-info.js https://raw.githubusercontent.com/Rabbit-Spec/Surge/Master/Module/Panel/Sub-info/Moore/Sub-info.js || echo "Sub-info.js下载失败"
          curl -o QuantumultX/Task/net-lsp-x.js https://raw.githubusercontent.com/xream/scripts/main/surge/modules/network-info/net-lsp-x.js || echo "net-lsp-x.js下载失败"

      - name: 同步 Rewrite 重写
        run: |
          curl -L -H "User-Agent: Surge iOS/3367" -o Rewrite/boxjs_QX.conf https://github.com/chavyleung/scripts/raw/master/box/rewrite/boxjs.rewrite.quanx.conf
          curl -L -H "User-Agent: Surge iOS/3367" -o Rewrite/boxjs.js https://raw.githubusercontent.com/chavyleung/scripts/master/box/chavy.boxjs.js || echo "boxjs.js下载失败"
          curl -o Rewrite/10099Get_Cookie.js https://raw.githubusercontent.com/wuhuhuuuu/study/main/Scripts/ChinaBroadnet/ChinaBroadnet.cookie.js || echo "10099Get_Cookie.js下载失败"
          curl -o Rewrite/10099.js https://raw.githubusercontent.com/wuhuhuuuu/study/main/Scripts/ChinaBroadnet/ChinaBroadnet.js || echo "10099.js下载失败"
          curl -o Rewrite/pornhub.js https://raw.githubusercontent.com/ddgksf2013/Scripts/master/pornhub.js || echo "pornhub.js下载失败"
          curl -o Rewrite/Weibo.conf https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/AdBlock/Weibo.conf || echo "Weibo.conf下载失败"
          curl -o Rewrite/BilibiliDailyBonus.js https://raw.githubusercontent.com/ClydeTime/BiliBili/main/js/BiliBiliDailyBonus.js || echo "BilibiliDailyBonus.js下载失败"
          curl -o Rewrite/jijianhuilv.js https://raw.githubusercontent.com/chxm1023/Rewrite/main/jijianhuilv.js || echo "jijianhuilv.js下载失败"
          curl -o Rewrite/WeChat110.js https://raw.githubusercontent.com/zZPiglet/Task/master/asset/UnblockURLinWeChat.js || echo "WeChat110.js下载失败"
          curl -o Rewrite/sms-forward.js https://raw.githubusercontent.com/ChinaTelecomOperators/SMSForward/main/sms-forward.js || echo "sms-forward.js下载失败"
          curl -x "${{ secrets.SOCKS_PROXY }}" -L -H "User-Agent: Loon/886 CFNetwork/3826.600.41 Darwin/24.6.0" -o Rewrite/Amap_remove_ads.js https://kelee.one/Resource/JavaScript/Amap/Amap_remove_ads.js || echo "Amap_remove_ads.js下载失败"
          curl -v -L -H "User-Agent: Loon/886 CFNetwork/3826.600.41 Darwin/24.6.0" -o Rewrite/Umetrip_remove_ads.js https://kelee.one/Resource/JavaScript/Umetrip/Umetrip_remove_ads.js || echo "Umetrip_remove_ads.js下载失败"

      - name: 同步 Rule 规则
        run: |
          curl -L -H "User-Agent: Surge iOS/3367" -o Rules/Apple.list https://raw.githubusercontent.com/ConnersHua/RuleGo/refs/heads/master/Surge/Ruleset/Extra/Apple/Apple.list || echo "Apple.list下载失败"
          curl -o Rules/Sukka_ai.conf https://ruleset.skk.moe/List/non_ip/ai.conf || echo "Sukka_ai.conf下载失败"
          curl -o Rules/Sukka_icloud_private_relay.conf https://ruleset.skk.moe/List/domainset/icloud_private_relay.conf || echo "Sukka_icloud_private_relay.conf下载失败"

      - name: 同步 sgmodule 文件
        run: |
          # 下载各个 sgmodule 文件到 sgmodule 目录，针对特定文件设置自定义 User-Agent
          # 使用 -L 参数跟随重定向，确保下载最新发布版本的文件
          curl -L -H "User-Agent: Surge iOS/3367" -o Module/iRingo.Location.sgmodule https://github.com/NSRingo/GeoServices/releases/latest/download/iRingo.Location.sgmodule || echo "iRingo.Location.sgmodule下载失败"
          curl -L -H "User-Agent: Surge iOS/3367" -o Module/iRingo.WeatherKit.sgmodule https://github.com/NSRingo/WeatherKit/releases/latest/download/iRingo.WeatherKit.sgmodule || echo "iRingo.WeatherKit.sgmodule下载失败"
          curl -L -H "User-Agent: Surge iOS/3367" -o Module/iRingo.Maps.sgmodule https://github.com/NSRingo/GeoServices/releases/latest/download/iRingo.Maps.sgmodule || echo "iRingo.Maps.sgmodule下载失败"
          curl -o Module/Block_HTTPDNS.sgmodule https://raw.githubusercontent.com/VirgilClyne/GetSomeFries/main/sgmodule/HTTPDNS.Block.sgmodule || echo "Block_HTTPDNS.sgmodule下载失败"
          curl -L -H "User-Agent: Surge iOS/3367" -o Module/boxjs_surge.sgmodule https://github.com/chavyleung/scripts/raw/master/box/rewrite/boxjs.rewrite.surge.sgmodule || echo "boxjs_surge.sgmodule下载失败"
          curl -o Module/App解锁合集.sgmodule https://raw.githubusercontent.com/chxm1023/Script_X/main/Collections.sgmodule || echo "App解锁合集.sgmodule下载失败"
          curl -o Module/10010_ad.sgmodule https://raw.githubusercontent.com/QingRex/LoonKissSurge/main/Surge/Official/%E4%B8%AD%E5%9B%BD%E8%81%94%E9%80%9A%E5%8E%BB%E5%B9%BF%E5%91%8A.sgmodule || echo "10010_ad.sgmodule下载失败"
          curl -o Module/JD_Helper.sgmodule https://raw.githubusercontent.com/githubdulong/Script/master/Surge/jd_price2.sgmodule || echo "JD_Helper.sgmodule下载失败"
          curl -o Module/YouTube_Lite.sgmodule https://raw.githubusercontent.com/Maasea/sgmodule/master/YouTube.Lite.sgmodule || echo "YouTube_Lite.sgmodule下载失败"
          curl -o Module/WeChat110.sgmodule https://raw.githubusercontent.com/QingRex/LoonKissSurge/refs/heads/main/Surge/Beta/%E5%BE%AE%E4%BF%A1%E5%A4%96%E9%83%A8%E9%93%BE%E6%8E%A5%E8%A7%A3%E9%94%81.beta.sgmodule || echo "WeChat110.sgmodule下载失败"
          curl -o Module/keleePlugin.sgmodule https://raw.githubusercontent.com/Yu9191/Rewrite/refs/heads/main/pluginhub.sgmodule || echo "keleePlugin.sgmodule下载失败"
          
          # 遍历 sgmodule 目录下的所有 .sgmodule 文件，批量替换或插入参数内容
          for file in Module/*.sgmodule; do
            # 检查文件是否存在且不为空，避免处理空文件
            if [ -s "$file" ]; then
              echo "处理文件: $file"
              # 检查文件是否包含 #!category 参数
              if grep -q "^#!category" "$file"; then
                # 如果存在，则替换现有内容
                sed -i '/^#!category[ =]/ s/.*/#!category=🌐 Remote_Module/' "$file"
              else
                # 如果不存在，则在文件第一行插入 #!category 参数
                sed -i '1i #!category=🌐 Remote_Module' "$file"
              fi
            else
              echo "文件 $file 为空或不存在，跳过处理"
            fi
          done

      - name: QX HTTP 后端文件
        run: |
          curl -o QuantumultX/http_backend/backend-icloud-to-http.js https://raw.githubusercontent.com/crossutility/Quantumult-X/master/backend-icloud-to-http.js || echo "backend-icloud-to-http.js下载失败"

      - name: GEOIP 数据库
        run: |
          curl -o Geo_data/Country.mmdb https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb
          curl -o Geo_data/geoip.dat https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip.dat
          curl -o Geo_data/geosite.dat https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat

      - name: 检查文件是否有变更
        id: changes
        run: |
          git add QuantumultX/ Rewrite/ Rules/ Module/ Module/ Geo_data/
          if git diff --cached --quiet; then
            echo "未检测到文件变更"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "检测到文件变更"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: 提交并推送变更
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -m '同步机器人: Update Finished【👌】'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
