name: 自动抓取Sync机器人

on:
  schedule:
    # 每天 UTC 时间 3 点 0 分运行一次
    - cron: '0 3 * * *'
  workflow_dispatch:
    # 手动触发

permissions:
  contents: write

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - name: 设置 Node.js 20 环境
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 检出代码仓库
        uses: actions/checkout@v3

      - name: QX解析器 & Task脚本
        run: |
          curl -o QuantumultX/general/resource-parser.js https://raw.githubusercontent.com/KOP-XIAO/QuantumultX/master/Scripts/resource-parser.js || echo "Error downloading resource-parser.js"
          curl -o QuantumultX/Task/check.js https://raw.githubusercontent.com/MCdasheng/QuantumultX/main/Streaming/check.js || echo "Error downloading check.js"
          curl -o QuantumultX/Task/Sub-info.js https://raw.githubusercontent.com/Rabbit-Spec/Surge/Master/Module/Panel/Sub-info/Moore/Sub-info.js || echo "Error downloading Sub-info.js"
          curl -o QuantumultX/Task/net-lsp-x.js https://raw.githubusercontent.com/xream/scripts/main/surge/modules/network-info/net-lsp-x.js || echo "Error downloading net-lsp-x.js"

      - name: 同步 Rewrite 重写
        run: |
          curl -L -H "User-Agent: Surge iOS/3367" -o Rewrite/boxjs_QX.conf https://github.com/chavyleung/scripts/raw/master/box/rewrite/boxjs.rewrite.quanx.conf
          curl -L -H "User-Agent: Surge iOS/3367" -o Rewrite/boxjs.js https://raw.githubusercontent.com/chavyleung/scripts/master/box/chavy.boxjs.js || echo "Error downloading boxjs.js"
          curl -o Rewrite/10099Get_Cookie.js https://raw.githubusercontent.com/wuhuhuuuu/study/main/Scripts/ChinaBroadnet/ChinaBroadnet.cookie.js || echo "Error downloading 10099Get_Cookie.js"
          curl -o Rewrite/10099.js https://raw.githubusercontent.com/wuhuhuuuu/study/main/Scripts/ChinaBroadnet/ChinaBroadnet.js || echo "Error downloading 10099.js"
          curl -o Rewrite/pornhub.js https://raw.githubusercontent.com/ddgksf2013/Scripts/master/pornhub.js || echo "Error downloading pornhub.js"
          curl -o Rewrite/Weibo.conf https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/AdBlock/Weibo.conf || echo "Error downloading Weibo.conf"
          curl -o Rewrite/BilibiliDailyBonus.js https://raw.githubusercontent.com/ClydeTime/BiliBili/main/js/BiliBiliDailyBonus.js || echo "Error downloading BilibiliDailyBonus.js"
          curl -o Rewrite/jijianhuilv.js https://raw.githubusercontent.com/chxm1023/Rewrite/main/jijianhuilv.js || echo "Error downloading jijianhuilv.js"
          curl -o Rewrite/WeChat110.js https://raw.githubusercontent.com/zZPiglet/Task/master/asset/UnblockURLinWeChat.js || echo "Error downloading WeChat110.js"
          curl -o Rewrite/sms-forward.js https://raw.githubusercontent.com/ChinaTelecomOperators/SMSForward/main/sms-forward.js || echo "Error downloading sms-forward.js"

      - name: 同步 Rule 规则
        run: |
          curl -L -H "User-Agent: Surge iOS/3367" -o Rules/Apple.list https://kelee.one/Tool/Loon/Lsr/AppStore.lsr || echo "Error downloading Apple.list"
          curl -o Rules/Sukka_ai.conf https://ruleset.skk.moe/List/non_ip/ai.conf || echo "Error downloading Sukka_ai.conf"
          curl -o Rules/Sukka_icloud_private_relay.conf https://ruleset.skk.moe/List/domainset/icloud_private_relay.conf || echo "Error downloading Sukka_icloud_private_relay.conf"

      - name: 同步 sgmodule 文件
        run: |
          # 下载各个 sgmodule 文件到 sgmodule 目录，针对特定文件设置自定义 User-Agent
          # 使用 -L 参数跟随重定向，确保下载最新发布版本的文件
          curl -L -H "User-Agent: Surge iOS/3367" -o Module/iRingo.Location.sgmodule https://github.com/NSRingo/GeoServices/releases/latest/download/iRingo.Location.sgmodule || echo "Error downloading iRingo.Location.sgmodule"
          curl -L -H "User-Agent: Surge iOS/3367" -o Module/iRingo.WeatherKit.sgmodule https://github.com/NSRingo/WeatherKit/releases/latest/download/iRingo.WeatherKit.sgmodule || echo "Error downloading iRingo.WeatherKit.sgmodule"
          curl -L -H "User-Agent: Surge iOS/3367" -o Module/iRingo.Maps.sgmodule https://github.com/NSRingo/GeoServices/releases/latest/download/iRingo.Maps.sgmodule || echo "Error downloading iRingo.Maps.sgmodule"
          curl -o Module/Block_HTTPDNS.sgmodule https://raw.githubusercontent.com/VirgilClyne/GetSomeFries/main/sgmodule/HTTPDNS.Block.sgmodule || echo "Error downloading Block_HTTPDNS.sgmodule"
          curl -L -H "User-Agent: Surge iOS/3367" -o Module/boxjs_surge.sgmodule https://github.com/chavyleung/scripts/raw/master/box/rewrite/boxjs.rewrite.surge.sgmodule || echo "Error downloading boxjs_surge.sgmodule"
          curl -o Module/App解锁合集.sgmodule https://raw.githubusercontent.com/chxm1023/Script_X/main/Collections.sgmodule || echo "Error downloading App解锁合集.sgmodule"
          curl -o Module/10010_ad.sgmodule https://raw.githubusercontent.com/QingRex/LoonKissSurge/main/Surge/Official/%E4%B8%AD%E5%9B%BD%E8%81%94%E9%80%9A%E5%8E%BB%E5%B9%BF%E5%91%8A.sgmodule || echo "Error downloading 10010_ad.sgmodule"
          curl -o Module/JD_Helper.sgmodule https://raw.githubusercontent.com/githubdulong/Script/master/Surge/jd_price2.sgmodule || echo "Error downloading JD_Helper.sgmodule"
          curl -o Module/YouTube_Lite.sgmodule https://raw.githubusercontent.com/Maasea/sgmodule/master/YouTube.Lite.sgmodule || echo "Error downloading YouTube_Lite.sgmodule"
          curl -o Module/WeChat110.sgmodule https://raw.githubusercontent.com/QingRex/LoonKissSurge/refs/heads/main/Surge/Beta/%E5%BE%AE%E4%BF%A1%E5%A4%96%E9%83%A8%E9%93%BE%E6%8E%A5%E8%A7%A3%E9%94%81.beta.sgmodule || echo "Error downloading WeChat110.sgmodule"
          
          # 遍历 sgmodule 目录下的所有 .sgmodule 文件，批量替换或插入参数内容
          for file in Module/*.sgmodule; do
            # 检查文件是否存在且不为空，避免处理空文件
            if [ -s "$file" ]; then
              echo "处理文件: $file"
              # 检查文件是否包含 #!category 参数
              if grep -q "^#!category" "$file"; then
                # 如果存在，则替换现有内容
                sed -i '/^#!category[ =]/ s/.*/#!category=🌐 Remote_Module/' "$file"
              else
                # 如果不存在，则在文件第一行插入 #!category 参数
                sed -i '1i #!category=🌐 Remote_Module' "$file"
              fi
            else
              echo "文件 $file 为空或不存在，跳过处理"
            fi
          done

      - name: QX HTTP 后端文件
        run: |
          curl -o QuantumultX/http_backend/backend-icloud-to-http.js https://raw.githubusercontent.com/crossutility/Quantumult-X/master/backend-icloud-to-http.js || echo "Error downloading backend-icloud-to-http.js"

      - name: GEOIP 数据库
        run: |
          curl -o Geo_data/Country.mmdb https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb
          curl -o Geo_data/geoip.dat https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip.dat
          curl -o Geo_data/geosite.dat https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat

      - name: 检查文件是否有变更
        id: changes
        run: |
          git add QuantumultX/ Rewrite/ Rules/ Module/ Module/ Geo_data/
          if git diff --cached --quiet; then
            echo "未检测到文件变更"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "检测到文件变更"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: 提交并推送变更
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -m '同步机器人: Update Finished【👌】'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
